---
title: "aus-case-study"
author: "Renee Albrecht"
date: "October 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load packages
library(tidyverse) # for general data wrangling and plotting
library(furrr) # for parallel operations on lists
library(lubridate) # for working with dates
library(sf) # for vector data 
library(raster) # for working with rasters
library(maps) # additional helpful mapping packages
library(maptools)
library(rgeos)
library(here)

```

```{r}
#Load Shapefiles

# World polygons from the maps package
world_shp <- sf::st_as_sf(maps::map("world", plot = FALSE, fill = TRUE))

#load eez polygons 
eezs <- read_sf('EEZ_land_union_v2_201410', layer = 'EEZ_land_v2_201410') 

#load coral sea downgrade polygon 
cs_dg <- read_sf('RA_PADDD_final') 
 

```

```{r}
## Import Data##

# Specify location of data directory
data_dir <-'fishing_effort'

# Create dataframe of filenames dates and filter to date range of interest

effort_files <- tibble(
  file = list.files(here(data_dir,'daily_csvs'), 
                    pattern = '.csv', recursive = T, full.names = T), 
  date = ymd(str_extract(file, 
                         pattern = '[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}')))

# Generate a vector of dates of interest using ymd from lubridate
effort_dates <- seq(ymd('2016-01-01'), ymd('2016-12-31'), by='days')

# Filter to files within our date range of interest
effort_files <- filter(effort_files, date %in% effort_dates)

plan(multiprocess) 
effort_df <- furrr::future_map_dfr(effort_files$file, .f = read_csv)

#Add date information
effort_df <- effort_df %>%
  mutate(year  = year(date),
         month = month(date))


```


```{r}
#Select Australia EEZ

aus <- eezs %>%
  filter(ISO_3digit == 'AUS')%>%
  dplyr::select(ISO_3digit, geometry)

aus_bbox <- sf::st_bbox(aus)

```


